version: '3'
services:
  main:
    restart: always
    build: ./
    command: >
      bash -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/workspace
    ports:
      - "8000:8000"
  redis:
    image: redis:6.2
  worker:
    build:
      context: .
    volumes:
      - ./:/workspace
    command: >
      sh -c "python manage.py rqworker default"
    depends_on:
      - redis
  pushpin:
    image: fanout/pushpin
    ports:
      - "8001:80"   # Default port where Pushpin listens for client requests
      - "5561:5561" # Control port for backend services to communicate
    depends_on:
      - main
    environment:
      PUSHPIN_ROUTE: "* http://main:8000/"